# Generated by Django 6.0.4 on 2026-09-27 06:54
# AUD-011: give StockAdjustmentLine explicit tenant ownership. The parent
# StockAdjustment row stays the single source of truth: the column is backfilled
# from it, then made NOT NULL.

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_tenant(apps, schema_editor):
    StockAdjustment = apps.get_model("inventory", "StockAdjustment")
    StockAdjustmentLine = apps.get_model("inventory", "StockAdjustmentLine")
    StockAdjustmentLine.objects.filter(tenant_id__isnull=True).update(
        tenant_id=Subquery(
            StockAdjustment.objects.filter(pk=OuterRef("adjustment_id")).values("tenant_id")[:1]
        )
    )
    orphans = StockAdjustmentLine.objects.filter(tenant_id__isnull=True).count()
    if orphans:
        raise RuntimeError(
            f"{orphans} stock adjustment line(s) could not be assigned a tenant "
            "from their parent adjustment; resolve them before migrating."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustmentline',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='stockadjustmentline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='stockadjustmentline',
            index=models.Index(fields=['tenant', 'adjustment'], name='inv_line_tenant_adj_idx'),
        ),
    ]
