# Generated by Django 6.0.4 on 2026-09-05 06:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_add_posted_fields'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Posted', 'Posted')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice', to='accounting.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Purchase Invoice',
                'verbose_name_plural': 'Purchase Invoices',
                'db_table': 'purchase_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=19)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaseinvoice')),
            ],
            options={
                'verbose_name': 'Purchase Invoice Line',
                'verbose_name_plural': 'Purchase Invoice Lines',
                'db_table': 'purchase_invoiceline',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'purchase_vendor',
            },
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchases.vendor'),
        ),
        migrations.CreateModel(
            name='PurchaseSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounts_payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('input_vat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Purchase Settings',
                'verbose_name_plural': 'Purchase Settings',
                'db_table': 'purchase_settings',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='unique_purchase_settings_per_tenant')],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['tenant'], name='purchase_ve_tenant__1e441e_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_active'], name='purchase_ve_is_acti_b077f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_vendor_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['tenant', 'status'], name='purchase_in_tenant__a7c089_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['vendor'], name='purchase_in_vendor__ceae59_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['tenant', 'vendor', 'invoice_date'], name='purchase_in_tenant__fa6507_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='unique_purchase_invoice_number_per_tenant'),
        ),
    ]
