# Generated by Django 6.0.4 on 2026-09-27 06:54
# AUD-011: give PurchaseInvoiceLine explicit tenant ownership. The parent
# PurchaseInvoice row stays the single source of truth: the column is backfilled
# from it, then made NOT NULL.

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_tenant(apps, schema_editor):
    PurchaseInvoice = apps.get_model("purchases", "PurchaseInvoice")
    PurchaseInvoiceLine = apps.get_model("purchases", "PurchaseInvoiceLine")
    PurchaseInvoiceLine.objects.filter(tenant_id__isnull=True).update(
        tenant_id=Subquery(
            PurchaseInvoice.objects.filter(pk=OuterRef("invoice_id")).values("tenant_id")[:1]
        )
    )
    orphans = PurchaseInvoiceLine.objects.filter(tenant_id__isnull=True).count()
    if orphans:
        raise RuntimeError(
            f"{orphans} purchase invoice line(s) could not be assigned a tenant "
            "from their parent invoice; resolve them before migrating."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
        ('inventory', '0002_stockadjustmentline_tenant_and_more'),
        ('purchases', '0002_add_product_to_purchase_invoiceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceline',
            index=models.Index(fields=['tenant', 'invoice'], name='purch_line_tenant_invoice_idx'),
        ),
    ]
