# Generated by Django 6.0.4 on 2026-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_balanced_entry_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
