# Generated by Django 6.0.4 on 2026-09-27 06:54
# AUD-011: give JournalEntryLine explicit tenant ownership. The parent
# JournalEntry row stays the single source of truth: the column is backfilled
# from it, then made NOT NULL.

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_tenant(apps, schema_editor):
    JournalEntry = apps.get_model("accounting", "JournalEntry")
    JournalEntryLine = apps.get_model("accounting", "JournalEntryLine")
    JournalEntryLine.objects.filter(tenant_id__isnull=True).update(
        tenant_id=Subquery(
            JournalEntry.objects.filter(pk=OuterRef("entry_id")).values("tenant_id")[:1]
        )
    )
    orphans = JournalEntryLine.objects.filter(tenant_id__isnull=True).count()
    if orphans:
        raise RuntimeError(
            f"{orphans} journal entry line(s) could not be assigned a tenant "
            "from their parent entry; resolve them before migrating."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_add_posted_fields'),
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryline',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='journalentryline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['tenant', 'entry'], name='acct_line_tenant_entry_idx'),
        ),
    ]
