# Generated by Django 6.0.4 on 2026-06-14 19:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blacklistedtoken'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Accountant', 'Accountant'), ('Manager', 'Manager')], default='Accountant', max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'db_table': 'accounts_invitation',
                'indexes': [models.Index(fields=['token'], name='accounts_in_token_be8e6c_idx'), models.Index(fields=['email'], name='accounts_in_email_571f5a_idx'), models.Index(fields=['tenant'], name='accounts_in_tenant__ba1c83_idx')],
                'constraints': [models.UniqueConstraint(fields=('email', 'tenant'), name='unique_pending_invitation_per_tenant')],
            },
        ),
    ]
