# Generated by Django 6.0.4 on 2026-06-17 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invitation'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
    ]
