# Generated by Django 6.0.4 on 2026-09-27 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tenant_field_not_null'),
        ('core', '0003_tenant_decommission_reason_tenant_decommissioned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='core.tenant'),
        ),
    ]
