# Generated by Django 6.0.4 on 2026-09-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_add_posted_fields'),
        ('core', '0001_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='direction',
            field=models.CharField(choices=[('Receivable', 'Receivable'), ('Payable', 'Payable')], default='Receivable', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchases.purchaseinvoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.salesinvoice'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['purchase_invoice'], name='sales_payme_purchas_91dbd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('invoice__isnull', False), ('purchase_invoice__isnull', True)), models.Q(('invoice__isnull', True), ('purchase_invoice__isnull', False)), _connector='OR'), name='check_payment_invoice_reference'),
        ),
    ]
