# Generated by Django 6.0.4 on 2026-09-05 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0003_payment_purchase_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.product'),
        ),
    ]
