# Generated by Django 6.0.4 on 2026-09-27 06:54
# AUD-011: give SalesInvoiceLine explicit tenant ownership. The parent
# SalesInvoice row stays the single source of truth: the column is backfilled
# from it, then made NOT NULL.

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_tenant(apps, schema_editor):
    SalesInvoice = apps.get_model("sales", "SalesInvoice")
    SalesInvoiceLine = apps.get_model("sales", "SalesInvoiceLine")
    SalesInvoiceLine.objects.filter(tenant_id__isnull=True).update(
        tenant_id=Subquery(
            SalesInvoice.objects.filter(pk=OuterRef("invoice_id")).values("tenant_id")[:1]
        )
    )
    orphans = SalesInvoiceLine.objects.filter(tenant_id__isnull=True).count()
    if orphans:
        raise RuntimeError(
            f"{orphans} sales invoice line(s) could not be assigned a tenant "
            "from their parent invoice; resolve them before migrating."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_add_posted_fields'),
        ('core', '0002_auditlog'),
        ('inventory', '0001_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0004_add_product_to_sales_invoiceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceline',
            index=models.Index(fields=['tenant', 'invoice'], name='sales_line_tenant_invoice_idx'),
        ),
    ]
